export const PROFESSIONALS_ACTION_TYPES = {
  FETCH_PROFESSIONALS_START: 'professionals/FETCH_PROFESSIONALS_START',
  FETCH_PROFESSIONALS_SUCCESS: 'professionals/FETCH_PROFESSIONALS_SUCCESS',
  FETCH_PROFESSIONALS_FAILURE: 'professionals/FETCH_PROFESSIONALS_FAILURE',
};
